services:
  movies:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movies
    ports:
     - "8080:80"
    restart: unless-stopped
    environment:
      - TMDB_API_URL=${TMDB_API_URL}
      - TMDB_API_HOST=${TMDB_API_HOST}
      - TMDB_BEARER_TOKEN=${TMDB_BEARER_TOKEN}
      - REMOTE_ENTRY_APP2_DETAILS=${REMOTE_ENTRY_APP2_DETAILS}
      - REMOTE_ENTRY_APP3_FAVORITES=${REMOTE_ENTRY_APP3_FAVORITES}
      - REMOTE_ENTRY_APP4_CAST=${REMOTE_ENTRY_APP4_CAST}
